name: merge_voice_coplain
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  uni_links2: ^0.6.0+2
  image: ^4.5.2
  url_launcher: ^6.2.5
  flutter_widget_from_html: ^0.15.3
  url_launcher_android: ^6.0.20
  flutter_html: 3.0.0-beta.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  flutter_sound: ^9.3.0
  record: ^5.0.5
  just_audio: ^0.9.38
  path_provider: ^2.1.3
  path: ^1.9.0
  google_fonts: ^6.2.1
  expandable: ^5.0.0
  smooth_page_indicator: ^1.0.0+2
  animated_text_kit: ^4.2.1
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.1.2 
  flutter_svg_provider: ^1.0.7
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  dotted_border: ^2.0.0
  http: ^1.1.2
  http_parser: ^4.0.2
  flutter_local_notifications: ^18.0.1
  jwt_decoder: ^2.0.1 
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2  # إضافة flutter_launcher_icons

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/bglogo.png"  # مسار الأيقونة الخاصة بك
  background_color: "#ffffff"
flutter:
  uses-material-design: true
  assets:
    - assets/images/

