platform :ios, '14.0' # النسخة المستهدفة، يمكن رفعها حسب الحاجة

# Flutter setup
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# تعريف flutter_root
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('Flutter', 'Generated.xcconfig'))
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get."
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # إضافة مكتبات Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # السماح باستخدام المعمارية المناسبة للمحاكي والجهاز
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64' # استثناء arm64 عند استخدام المحاكي
      config.build_settings['EXCLUDED_ARCHS[sdk=iphoneos*]'] = '' # السماح بجميع المعماريات على الجهاز الحقيقي
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
    end
  end
end









